sudo: true

language : python
python:
    - "3.7"
    - "3.6"
    - "3.4"
    - "3.3"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

env:
  - FLASK_VERSION=1.0.2

script: 
  - nosetest --with-coverage --cover-package=app
  - coveralls

after_success:
  - coveralls