sudo: true

language : python
python:
    - "3.7.0"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

script: 
  - nosetest --with-coverage --cover-package=app

after_success:
  - coveralls